// Registering
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// Auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

//Auth (Forgot Password)
export const PASSWORD_REQUEST = 'PASSWORD_REQUEST';
export const PASSWORD_SUCCESS = 'PASSWORD_REQUEST';
export const PASSWORD_FAILURE = 'PASSWORD_FAILURE';

// EventParent
export const CREATE_EVENT_PARENT_SUCCESS = 'CREATE_EVENT_PARENT_SUCCESS';
export const DELETE_EVENT_PARENT_SUCCESS = 'DELETE_EVENT_PARENT_SUCCESS';
export const GET_ALL_EVENT_PARENT_SUCCESS = 'GET_ALL_EVENT_PARENT_SUCCESS';
export const UPDATE_EVENT_PARENT_SUCCESS = 'UPDATE_EVENT_PARENT_SUCCESS';

// EventGroup
export const CREATE_EVENT_GROUP_SUCCESS = 'CREATE_EVENT_GROUP_SUCCESS';
export const DELETE_EVENT_GROUP_SUCCESS = 'DELETE_EVENT_GROUP_SUCCESS';
export const GET_ALL_EVENT_GROUP_SUCCESS = 'GET_ALL_EVENT_GROUP_SUCCESS';
export const UPDATE_EVENT_GROUP_SUCCESS = 'UPDATE_EVENT_GROUP_SUCCESS';

// EventType
export const CREATE_EVENT_TYPE_SUCCESS = 'CREATE_EVENT_TYPE_SUCCESS';
export const DELETE_EVENT_TYPE_SUCCESS = 'DELETE_EVENT_TYPE_SUCCESS';
export const GET_ALL_EVENT_TYPE_SUCCESS = 'GET_ALL_EVENT_TYPE_SUCCESS';
export const UPDATE_EVENT_TYPE_SUCCESS = 'UPDATE_EVENT_TYPE_SUCCESS';

// Event
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const GET_ALL_EVENT_SUCCESS = 'GET_ALL_EVENT_SUCCESS';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const CREATE_RECURRING_EVENT_SUCCESS = 'CREATE_RECURRING_EVENT_SUCCESS';
